# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('catch_date', models.DateField()),
                ('catch_time', models.TimeField()),
                ('form_of_fishing', models.CharField(max_length=30)),
                ('catch_latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('catch_longitude', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
