# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishprofile', '0003_auto_20170503_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
